# Generated by Django 3.2 on 2021-05-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210501_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of Endpoint')),
                ('url', models.URLField(verbose_name='URL of the Endpoint')),
                ('has_get', models.BooleanField(verbose_name='GET')),
                ('has_post', models.BooleanField(verbose_name='POST')),
                ('has_put', models.BooleanField(verbose_name='PUT')),
                ('has_patch', models.BooleanField(verbose_name='PATCH')),
                ('has_delete', models.BooleanField(verbose_name='DELETE')),
            ],
        ),
    ]
