# Generated by Django 3.2 on 2021-05-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizscore',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='quizscore',
            name='obtained_marks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Obtained Marks'),
        ),
    ]
