# Generated by Django 3.2 on 2021-05-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('STU', 'STUDENT'), ('TEACH', 'TEACHER')], default='STU', max_length=5, verbose_name='User type'),
        ),
    ]
